// Curated set of Lucide icons available for notes and categories. The stored
// value is the short key (e.g. "swords"); CampaignIcon resolves it to a component.
import {
  LuUser,
  LuUsers,
  LuSwords,
  LuShield,
  LuScroll,
  LuBookOpen,
  LuMap,
  LuMapPin,
  LuCastle,
  LuCrown,
  LuSkull,
  LuGem,
  LuKey,
  LuFlame,
  LuSparkles,
  LuMoon,
  LuSun,
  LuTrees,
  LuMountain,
  LuShip,
  LuHeart,
  LuStar,
  LuFlag,
  LuHouse,
  LuLandmark,
  LuCoins,
  LuFeather,
  LuGhost,
  LuBird,
  LuDog,
  LuFish,
  LuLeaf,
  LuAnchor,
  LuCompass,
  LuTarget,
  LuWand,
  LuBeer,
  LuDrama,
  LuNotebook,
} from 'react-icons/lu'

export const CAMPAIGN_ICONS = {
  user: LuUser,
  users: LuUsers,
  swords: LuSwords,
  shield: LuShield,
  scroll: LuScroll,
  book: LuBookOpen,
  map: LuMap,
  pin: LuMapPin,
  castle: LuCastle,
  crown: LuCrown,
  skull: LuSkull,
  gem: LuGem,
  key: LuKey,
  flame: LuFlame,
  sparkles: LuSparkles,
  moon: LuMoon,
  sun: LuSun,
  trees: LuTrees,
  mountain: LuMountain,
  ship: LuShip,
  heart: LuHeart,
  star: LuStar,
  flag: LuFlag,
  house: LuHouse,
  landmark: LuLandmark,
  coins: LuCoins,
  feather: LuFeather,
  ghost: LuGhost,
  bird: LuBird,
  dog: LuDog,
  fish: LuFish,
  leaf: LuLeaf,
  anchor: LuAnchor,
  compass: LuCompass,
  target: LuTarget,
  wand: LuWand,
  beer: LuBeer,
  drama: LuDrama,
  notebook: LuNotebook,
}

export const CAMPAIGN_ICON_NAMES = Object.keys(CAMPAIGN_ICONS)

// Renders a stored icon name, or `fallback` (a component) when unset/unknown.
export function CampaignIcon({ name, fallback: Fallback = null, ...props }) {
  const Icon = (name && CAMPAIGN_ICONS[name]) || Fallback
  return Icon ? <Icon {...props} /> : null
}
