// Curated set of Lucide icons available for notes and categories. The stored
// value is the short key (e.g. "swords"); CampaignIcon resolves it to a component.
import {
  LuUser,
  LuUsers,
  LuSwords,
  LuShield,
  LuScroll,
  LuBookOpen,
  LuMap,
  LuMapPin,
  LuCastle,
  LuCrown,
  LuSkull,
  LuGem,
  LuKey,
  LuFlame,
  LuSparkles,
  LuMoon,
  LuSun,
  LuTrees,
  LuMountain,
  LuShip,
  LuHeart,
  LuStar,
  LuFlag,
  LuHouse,
  LuLandmark,
  LuCoins,
  LuFeather,
  LuGhost,
  LuBird,
  LuDog,
  LuFish,
  LuLeaf,
  LuAnchor,
  LuCompass,
  LuTarget,
  LuWand,
  LuBeer,
  LuDrama,
  LuNotebook,
  LuAxe,
  LuVenetianMask,
  LuBrain,
  LuBone,
  LuDice5,
  LuSwitchCamera,
  LuTent,
  LuTowerControl,
  LuTreePine,
  LuWaves,
  LuSnowflake,
  LuDroplet,
  LuZap,
  LuWind,
  LuCloud,
  LuGlobe,
  LuLamp,
  LuLeafyGreen,
  LuLock,
  LuMartini,
  LuPawPrint,
  LuRat,
  LuRabbit,
  LuShell,
  LuShovel,
  LuSpade,
  LuSprout,
  LuTorus,
  LuTriangleAlert,
  LuUtensils,
  LuWheat,
  LuBackpack,
  LuBell,
  LuBomb,
  LuCircleDollarSign,
  LuClock,
  LuCrosshair,
  LuDrumstick,
  LuEgg,
  LuGavel,
  LuGraduationCap,
  LuHammer,
  LuHandHelping,
  LuHexagon,
  LuHourglass,
  LuPickaxe,
} from 'react-icons/lu'

export const CAMPAIGN_ICONS = {
  user: LuUser,
  users: LuUsers,
  swords: LuSwords,
  shield: LuShield,
  scroll: LuScroll,
  book: LuBookOpen,
  map: LuMap,
  pin: LuMapPin,
  castle: LuCastle,
  crown: LuCrown,
  skull: LuSkull,
  gem: LuGem,
  key: LuKey,
  flame: LuFlame,
  sparkles: LuSparkles,
  moon: LuMoon,
  sun: LuSun,
  trees: LuTrees,
  mountain: LuMountain,
  ship: LuShip,
  heart: LuHeart,
  star: LuStar,
  flag: LuFlag,
  house: LuHouse,
  landmark: LuLandmark,
  coins: LuCoins,
  feather: LuFeather,
  ghost: LuGhost,
  bird: LuBird,
  dog: LuDog,
  fish: LuFish,
  leaf: LuLeaf,
  anchor: LuAnchor,
  compass: LuCompass,
  target: LuTarget,
  wand: LuWand,
  beer: LuBeer,
  drama: LuDrama,
  notebook: LuNotebook,
  axe: LuAxe,
  mask: LuVenetianMask,
  brain: LuBrain,
  bone: LuBone,
  dice: LuDice5,
  portal: LuSwitchCamera,
  tent: LuTent,
  tower: LuTowerControl,
  pine: LuTreePine,
  waves: LuWaves,
  snowflake: LuSnowflake,
  droplet: LuDroplet,
  lightning: LuZap,
  wind: LuWind,
  cloud: LuCloud,
  globe: LuGlobe,
  lamp: LuLamp,
  herb: LuLeafyGreen,
  lock: LuLock,
  martini: LuMartini,
  paw: LuPawPrint,
  rat: LuRat,
  rabbit: LuRabbit,
  shell: LuShell,
  shovel: LuShovel,
  spade: LuSpade,
  sprout: LuSprout,
  ring: LuTorus,
  hazard: LuTriangleAlert,
  utensils: LuUtensils,
  wheat: LuWheat,
  backpack: LuBackpack,
  bell: LuBell,
  bomb: LuBomb,
  money: LuCircleDollarSign,
  clock: LuClock,
  crosshair: LuCrosshair,
  drumstick: LuDrumstick,
  egg: LuEgg,
  gavel: LuGavel,
  graduation: LuGraduationCap,
  hammer: LuHammer,
  help: LuHandHelping,
  hexagon: LuHexagon,
  hourglass: LuHourglass,
  pickaxe: LuPickaxe,
}

export const CAMPAIGN_ICON_NAMES = Object.keys(CAMPAIGN_ICONS)

// Renders a stored icon name, or `fallback` (a component) when unset/unknown.
export function CampaignIcon({ name, fallback: Fallback = null, ...props }) {
  const Icon = (name && CAMPAIGN_ICONS[name]) || Fallback
  return Icon ? <Icon {...props} /> : null
}
